#!/bin/sh

CC=/home/artpol/work/sigrand/projects/openwrt/midge.vlad.org.ua/trunk/openwrt-midge/staging_dir_mipsel/bin/mipsel-linux-uclibc-gcc
CXX=/home/artpol/work/sigrand/projects/openwrt/midge.vlad.org.ua/trunk/openwrt-midge/staging_dir_mipsel/bin/mipsel-linux-uclibc-g++
AR=/home/artpol/work/sigrand/projects/openwrt/midge.vlad.org.ua/trunk/openwrt-midge/staging_dir_mipsel/bin/mipsel-linux-uclibc-ar
RANLIB=/home/artpol/work/sigrand/projects/openwrt/midge.vlad.org.ua/trunk/openwrt-midge/staging_dir_mipsel/bin/mipsel-linux-uclibc-ranlib
export CXX AR RANLIB CC

STAGING_DIR=/home/artpol/OpenWRT/staging_dir_mipsel/
make LDFLAGS="-L${STAGING_DIR}/usr/lib -L${STAGING_DIR}/lib -static" all

