#***********************************************************************************
#
#	Sigrand EOC management server general Makefile
#	Written 2007 by Artem U. Polyakov <artpol84@gmail.com>
#	
#***********************************************************************************

USE_KDB=@USE_KDB@

TOPDIR=$(PWD)

include $(TOPDIR)/version.mk

INCLUDES=-I$(TOPDIR)/include/
INCLUDES += -I$(TOPDIR)/libconfig/
CPPFLAGS=$(INCLUDES) -DEOC_VER="\"$(EOC_VER)\""


.PHONY: generic engine devs utils db app-if

TARGS :=generic engine devs utils local db app-if
OBJECTS := build/*.o 

#ifeq (USE_KDB,0)
#	OBJECTS += libconfig/.libs/libconfig++.a
#endif

CC=@CROSS_PREFIX@gcc
CXX=@CROSS_PREFIX@g++
AR=@CROSS_PREFIX@ar
RANLIB=@CROSS_PREFIX@ranlib

export CXX AR RANLIB CC TOPDIR INCLUDES CPPFLAGS

all-mips: $(TARGS) 
	$(CC) $(CPPFLAGS) -c md5.c
	$(CC) $(CPPFLAGS) -DSHELL -c kdb.c 
	$(CXX) $(CPPFLAGS) -o eocd eocd.cpp md5.o kdb.o $(OBJECTS) 

local: EOC_main.o EOC_pci.o
	cp $^ build/    

engine:
	make all -C engine/ 
generic:
	make all -C generic/ 
devs:
	make all -C devs/ 
utils:
	make all -C utils/ 
db:
	make all -C db/ 
app-if:
	make all -C app-if/ 


clean:
	make -C engine clean
	make -C generic clean
	make -C devs clean
	make -C utils clean
	make -C db clean
	make -C app-if clean
	rm -f *.o
	rm -f result eocd
	rm -f build/*.o


ARCH_FILES=app-if build CHECK db devs engine eocd.conf eocd.cpp EOC_main.cpp \
generic include main.cpp Makefile.tmpl system TODO.txt utils

tar: clean
	tar --exclude="\.svn" -cjvf tar/eocd.tar.bz2 $(ARCH_FILES)
