/*
 * EOC_poller_req:
 *	EOC requests generation handlers.
 *	Requests generated by type and destination address
 *	Prototype:
 *	    EOC_msg *(*request_handler_t)(req_mode mode,unit src,unit dst,unsigned char type);
 */
#include <generic/EOC_requests.h>
#include <generic/EOC_msg.h>
#include <db/EOC_db.h>
#include <engine/EOC_handlers.h>

EOC_msg *
_req_discovery(sched_state stat,sched_elem el,EOC_config *cfg)
{
    if( el.type != REQ_DISCOVERY )
	return NULL;
    EOC_msg *m = new EOC_msg(REQ_DISCOVERY_SZ);
    m->msize();
    // TODO: make as exception!!!
    if( !m->mptr() )
	return NULL;
    req_discovery *req = (req_discovery *)m->payload();
    req->hop = 0;
    m->src(el.src);
    m->dst(el.dst);
    m->type(REQ_DISCOVERY);
    return m;
}


EOC_msg *
_req_inventory(sched_state stat,sched_elem el,EOC_config *cfg)
{
    if( el.type != REQ_INVENTORY )
	return NULL;
    EOC_msg *m = new EOC_msg(REQ_INVENTORY_SZ);
    // TODO: make as exception!!!
    if( !m->mptr() )
	return NULL;
    req_inventory *req = (req_inventory *)m->payload();
    m->src(el.src);
    m->dst(el.dst);
    m->type(REQ_INVENTORY);
    return m;
}

EOC_msg *
_req_configure(sched_state stat,sched_elem el,EOC_config *cfg)
{
    if( el.type != REQ_CONFIGURE )
	return NULL;
    EOC_msg *m = new EOC_msg(REQ_CONFIGURE_SZ);
    // TODO: make as exception!!!
    if( !m->mptr() )
	return NULL;
    req_configure *req = (req_configure *)m->payload();
    m->src(el.src);
    m->dst(el.dst);
    m->type(REQ_CONFIGURE);
    switch( stat ){
    case EOC_scheduler::Setup:
	req->conf_type = 0;
    case EOC_scheduler::Normal:
	req->conf_type = 1;
    }
    req->loop_attn = cfg->loop_attn(el.dst);
    req->snr_marg = cfg->snr_marg(el.dst);
    return m;
}

