/*
 * EOC_poller_req:
 *	EOC requests generation functions.
 *	Requests generated by type and destination address
 *	Prototype:
 *	    EOC_msg *(*request_handler_t)();
 */
#include <generic/EOC_requests.h>
#include <generic/EOC_msg.h>

EOC_msg *
_req_discovery(EOC_db *db,unit src,unit dst,unsigned char type)
{
    if( type != REQ_DISCOVERY )
	return -1;
    EOC_msg *m = new EOC_msg(REQ_DISCOVERY_SZ);
    // TODO: make as exception!!!
    if( !m->mptr() )
	return -ENOMEM;
    req_discovery *req = (req_discovery *)m->payload();
    req->hop = 0;
    m->src(stu_c);
    m->dst(dst);
    m->type(REQ_DISCOVERY);
    return m;
}
